[general]
min_fan1_speed = 1700	# put the *lowest* value of "cat /sys/devices/platform/applesmc.768/fan*_min"
max_fan1_speed = 1900	# put the *highest* value of "cat /sys/devices/platform/applesmc.768/fan*_max"
low_temp = 55
high_temp = 75
max_temp = 90
polling_interval = 5
